### ISSUE TITLE
RuntimeError: NCCL communicator was aborted on rank 6.  Original reason for failure was: [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085,  OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801754 milliseconds before timing out.

### ISSUE THREAD

**Issue by HiAleeYang** [ShiqiYu/OpenGait#89]
## System information (version)

- Pytorch => :1.9
- Operating System / Platform => :Ubuntu 16.04:
- Cuda => :11.4:

in config file yaml
- num_worker: 1
- enable_float16: false
- batch_size: 8
- PK(4,64)

## Detailed description
I use the DDP training with 8 GPUS in CASIA-B dataset.It will be ok in early stage, but in last few iteration , it occurs the error of 

[2022-10-12 12:41:33] [INFO]: Iteration 32700, Cost 17.76s, triplet_loss=0.1912, triplet_hard_loss=0.9691, triplet_loss_num=1641.7500, triplet_mean_dist=6.7157
[2022-10-12 12:41:34] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:34] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:35] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:35] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:36] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:36] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:37] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:38] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:39] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:40] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[2022-10-12 12:41:40] [WARNING]: Find the loss sum less than 1e-9 but the training process will continue!
[E ProcessGroupNCCL.cpp:737] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801504 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801562 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801638 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801698 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801712 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801754 mill
iseconds before timing out.
[E ProcessGroupNCCL.cpp:737] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801777 mill
iseconds before timing out.

And the following Traceback is 
`
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/modeling/base_model.py", line 401, in run_train
    for inputs in model.train_loader:
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    data = self._next_data()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/modeling/base_model.py", line 401, in run_train
    return self._process_data(data)    
for inputs in model.train_loader:  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data

  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    self._try_put_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
    return self._process_data(data)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    index = self._next_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 28, in __iter__
    self._try_put_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
    self.dataset.label_set, self.batch_size[0])
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 61, in sync_random_sample_list
    torch.distributed.broadcast(idx, src=0)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    index = self._next_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 2.  Original reason for failure was: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085,
 OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801698 milliseconds before timing out.
    return next(self._sampler_iter)  # may raise StopIteration
File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 28, in __iter__
    self.dataset.label_set, self.batch_size[0])
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 61, in sync_random_sample_list
    torch.distributed.broadcast(idx, src=0)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085,
 OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801777 milliseconds before timing out.
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
        Model.run_train(model)run_model(cfgs, training)

  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/modeling/base_model.py", line 401, in run_train
  File "opengait/main.py", line 54, in run_model
    Model.run_train(model)
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/modeling/base_model.py", line 401, in run_train
    for inputs in model.train_loader:
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    for inputs in model.train_loader:
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    data = self._next_data()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    return self._process_data(data)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    self._try_put_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
    self._try_put_index()
File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1353, in _try_put_index
Traceback (most recent call last):
  File "opengait/main.py", line 71, in <module>
    index = self._next_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    index = self._next_index()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 642, in _next_index
    run_model(cfgs, training)
  File "opengait/main.py", line 54, in run_model
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 28, in __iter__
    Model.run_train(model)
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/modeling/base_model.py", line 401, in run_train
    self.dataset.label_set, self.batch_size[0])
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 61, in sync_random_sample_list
    torch.distributed.broadcast(idx, src=0)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 28, in __iter__
    self.dataset.label_set, self.batch_size[0])
      File "/home/fuyang/OUMVLP/PoseOpenGait/opengait/data/sampler.py", line 61, in sync_random_sample_list
for inputs in model.train_loader:
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    torch.distributed.broadcast(idx, src=0)
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1193, in broadcast
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 4.  Original reason for failure was: [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085,
 OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801638 milliseconds before timing out.    
data = self._next_data()
  File "/home/fuyang/anaconda3/envs/opengait/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    work = default_pg.broadcast([tensor], opts)
RuntimeError: NCCL communicator was aborted on rank 7.  Original reason for failure was: [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=382085,
 OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1801712 milliseconds before timing out.
    return self._process_data(data)
`

## Issue submission checklist
 - [ ] I checked the problem with documentation, FAQ, issues, and have not found solution.

**Comment by darkliang** [comment]
We haven't had this problem, but I think it might be because your code is taking a long time at a certain step.

**Comment by darkliang** [comment]
https://github.com/ShiqiYu/OpenGait/blob/c2a48191e33ba4da910c2d1afe3b236199590dec/opengait/main.py#L60

**Comment by HiAleeYang** [comment]
Thank you very much!

**Comment by hxi667** [comment]
> Thank you very much!

Has your problem been solved by increasing the timeout period? I had the same problem, but the difference is that my error occurred during the testing phase during training

**Comment by zmtttt** [comment]
hello  have you sloved the problem？ I met the same problem，the first iteration works fine ，but the second iteration and the second forward-step was strucked and then make nccl erros，I use megatron.

> > Thank you very much!
> 
> Has your problem been solved by increasing the timeout period? I had the same problem, but the difference is that my error occurred during the testing phase during training
